/* Variation of parameters */

/* y'' - y = x */
ode2('diff(y,x,2)-y=0,y,x);
yh:rhs(%);
y1:%e^x; y2:%e^(-x); r:x;
A: matrix([y1,y2],[diff(y1,x),diff(y2,x)]);
W: determinant(A);
u1:integrate(-y2*r/W,x);
u2:integrate(y1*r/W,x);
yp:ratsimp(u1*y1+u2*y2);
'y=yh+yp;

/* y'' + y = sec(x) */
ode2('diff(y,x,2)+y=0,y,x);
yh:rhs(%);
y1:sin(x); y2:cos(x); r:sec(x);
A: matrix([y1,y2],[diff(y1,x),diff(y2,x)]);
W: determinant(A);
u1:integrate(-y2*r/W,x);
u2:integrate(-y1*r/W,x);
yp:ratsimp(u1*y1+u2*y2);
'y=yh+yp;

/* y'' - 2y' + y = e^x / x */
ode2('diff(y,x,2)-2*('diff(y,x))+y=0,y,x);
yh:rhs(%);
y1:x*(%e^x); y2:%e^x; r:(%e^x)/x;
A: matrix([y1,y2],[diff(y1,x),diff(y2,x)]);
W: determinant(A);
u1:integrate(-y2*r/W,x);
u2:integrate(y1*r/W,x);
yp:ratsimp(u1*y1+u2*y2);
'y=yh+yp;

/* y'' + 2y' + y = 2x sin(x) */
ode2('diff(y,x,2)+2*'diff(y,x)+y=0,y,x);
yh:rhs(%);
y1:x*%e^(-x); y2:%e^(-x); r:2*x*sin(x);
A:matrix([y1,y2],[diff(y1,x),diff(y2,x)]);
w:determinant(A);
u1:integrate(-y2*r/w,x);
u2:integrate(y1*r/w,x);
yp:ratsimp(u1*y1+u2*y2);
'y=yp+yh;
