/* Cauchy problem for first-order PDEs */

/* u(x+y)p + u(x-y)q = x^2 + y^2,  u = 0 on y = 2x */
a(x,y,u):=u*(x+y);
b(x,y,u):=u*(x-y);
c(x,y,u):=x^2+y^2;
dx/a(x,y,u)=dy/b(x,y,u);
integrate(x,x)-integrate(y,y)-x*y;
φ:%=c1;
ratsimp(x*a(x,y,u)-y*b(x,y,u)-u*c(x,y,u));
integrate(x,x)-integrate(y,y)-integrate(u,u);
ψ:%=c2;
f(lhs(φ),lhs(ψ))=0;
ev(φ,y=2*x,u=0);
ev(ψ,y=2*x,u=0);
ratsimp((2/7)*lhs(φ)-(2/3)*lhs(ψ)=0);
solve((4·y^2-6·x·y-4·x^2+7·u^2)/21,u);
kill(all);

/* p - q = 1,  u(x,0) = x^2 */
a(x,y,u):=1;
b(x,y,u):=-1;
c(x,y,u):=1;
dx/a(x,y,u)=dy/b(x,y,u);
integrate(1,x)+integrate(1,y);
φ:%=c1;
plot3d([sqrt((4*x^2-4*y^2+6*x*y)/7),-sqrt((4*x^2-4*y^2+6*x*y)/7),[x,-5,5],[y,-5,5]]);
dy/b(x,y,u)=du/c(x,y,u);
integrate(1,u)+integrate(1,y);
ψ:%=c2;
f(lhs(φ),lhs(ψ))=0;
ev(φ,y=0,u=x^2);
ev(ψ,y=0,u=x^2);
ratsimp((lhs(φ))^2-lhs(ψ)=0);
plot3d([(y^2+(2*x-1)*y+x^2),y^2+(2*x-1)*y+x^2,[x,-5,5],[y,-5,5]]);

/* (y-u)p + (u-x)q = x - y,  u = 0 on xy = 1 */
a(x,y,u):=y-u;
b(x,y,u):=u-x;
c(x,y,u):=x-y;
integrate(1,x)+integrate(1,y)+integrate(1,u);
φ:%=c1;
integrate(x,x)+integrate(y,y)+integrate(u,u);
ψ:%=c2;
f(lhs(φ),lhs(ψ))=0;
ev(φ,y=x^(-1),u=0);
ev(ψ,y=x^(-1),u=0);
ratsimp((lhs(φ)^2)-2*lhs(ψ)=2);
solve((2*x+2*u)*y+2*u*x=2,u);
plot3d([(-(x*y-1)/(y+x)),[x,-5,5],[y,-5,5]]);
a(x,y,u):=1;
b(x,y,u):=-1;
c(x,y,u):=1;
integrate(1,x)+integrate(1,y);
Φ:%=c1;
integrate(1,u)+integrate(1,y);
Ψ:%=c2;
f(lhs(Φ),lhs(Ψ))=0;
