/* Plotting the characteristics for the first order pde */

/* Q: (y-u)p+yq=x-y */

/* color=blue,key="curve 1",parametric(rhs(sol1[1]),rhs(sol1[2]),rhs(sol1[3]),t,-1,1), color=pink,key="curve 2",parametric(rhs(sol2[1]),rhs(sol2[2]),rhs(sol2[3]),t,-1,1), */

eqn1:diff(x(t),t)=y(t)+u(t)$
eqn2:diff(y(t),t)=y(t)$
eqn3:diff(u(t),t)=x(t)-y(t)$
sol:(desolve([eqn1,eqn2,eqn3],[x(t),y(t),u(t)]))$
sol1:ev(sol,x(0)=1,y(0)=3,u(0)=30)$
sol2:ev(sol,x(0)=10,y(0)=2,u(0)=30)$
sol3:ev(sol,x(0)=5,y(0)=20,u(0)=30)$
wxdraw3d(xlabel="X",ylabel="Y",zlabel="U",title="Characteristic Curves",
color=magenta,key="curve 3",parametric(rhs(sol3[1]),rhs(sol3[2]),rhs(sol3[3]),t,-1,1))$
