/* Plotting Higher Order Solution Families */

/* We will plot the family of solutions of the given third order diff eqn: 1. y''' - 5y'' + 8y' - 4y = 0 */

eqn:diff(y(x),x,3) - 5*diff(y(x),x,2) + 8*diff(y(x),x) - 4*y(x) = 0;
sol:desolve(eqn,y(x));
sol1:ev(sol,y(0)=c1,diff(y(x),x)=c2,diff(y(x),x,2)=c3);
v1:ev(sol1,c1=1,c2=2,c3=3)$
v2:ev(sol1,c1=2,c2=1,c3=3)$
v3:ev(sol1,c1=1,c3=2,c3=2)$
v4:ev(sol1,c1=2,c2=3,c3=1)$
v5:ev(sol1,c1=3,c2=1,c3=2)$
v6:ev(sol1,c1=3,c2=2,c3=1)$,
wxplot2d([rhs(v1),rhs(v2),rhs(v3),rhs(v4),rhs(v5),rhs(v6)],[x,2,4],[legend,"1","2","3","4","5","6"])$

/* 2.y'''-12y''+48y'-64y = 12 - 32exp(-8x)+2exp(4x) */

eqn:diff(y(x),x,3) - 12*diff(y(x),x,2) + 48*diff(y(x),x) - 64*y(x) = 12 - 32*%e^(-8*x)+2*%e^(4*x);
sol:desolve(eqn,y(x));
sol1:ev(sol,y(0)=c1,diff(y(x),x)=c2,diff(y(x),x,2)=c3);
v1:ev(sol1,c1=1,c2=2,c3=3)$
v2:ev(sol1,c1=2,c2=1,c3=3)$
v3:ev(sol1,c1=1,c3=2,c3=2)$
v4:ev(sol1,c1=2,c2=3,c3=1)$
v5:ev(sol1,c1=3,c2=1,c3=2)$
v6:ev(sol1,c1=3,c2=2,c3=1)$,
wxplot2d([rhs(v1),rhs(v2),rhs(v3),rhs(v4),rhs(v5),rhs(v6)],[x,2,4],[legend,"1","2","3","4","5","6"])$

/* General Programs (that are more fun!) */

if(2=3)then
print("abc");

for i: 1 thru 10 do
print(i)$

s:0;
for i:1 while(i<=10) do
s:s+i;
print(s)$

block (s:0,for i:1 while(i<=10) do s:s+i, print(s))$

block(s:1,
    for i:1 while(i<=10)do
    s:s*i,
    print(s))$

block(
    n: read ("enter the number to find its factorial"),
    s:1,
    for i:1 while(i<=n)do
    s:s*i,
    print("The factorial of",n,"is",s))$
